### ISSUE TITLE
Define a mapping between the RedCap and ElabFTW survey definition

### ISSUE THREAD

**Issue by JuliaSprenger** [INT-NIT/DigLabTools#60]
The csv survey definition based on the RedCap structure is very extensive, so only a subset of the csv columns should be mandatory to create an ElabFTW survey. This mapping should be defined in a dedicated file so it can be customized if needed. A good format to define this mapping would be json. Add documentation of the mapping. Note: In case of functionality missing on the ElabFTW side, report this as an issue to be handled by ElabFTW.

![Image](https://user-images.githubusercontent.com/74175986/192277939-36c1b21e-05a1-4e3d-8f08-54e4048b552d.png)

Here is a mapping representing the difference between csv and json. The goal is to allow a better generation of json files based on csv

**Comment by JuliaSprenger** [comment]
@killianrochet For the points in your table that can not be translated to ELab, can you check if a corresponding issue / PR exists already for ElabFTW? If not we should open an issue to start a discussion on potentially extending ElabFTW.

**Comment by killianrochet** [comment]
https://github.com/elabftw/elabftw/issues/3703
