### ISSUE TITLE
Add clean test file setup on the server side

### ISSUE THREAD

**Issue by JuliaSprenger** [INT-NIT/DigLabTools#76]
Here you are assuming that there is already a specific experiment on the server with experiment_id 232. This might be the case for our current server, but is not the case for any elab server. Could you rewrite the test in a way that it first uploads an experiment and then downloads it again, so you can compare the content you uploaded vs the content you donwloaded? See also the approach in the corresponding redcap test: https://github.com/INT-NIT/DigLabTools/blob/8fe6bece2d622a79446b4229e33e2bf0d7dc1e53/redcap_bridge/test_redcap/test_server_interface.py#L75

_Originally posted by @JuliaSprenger in https://github.com/INT-NIT/DigLabTools/pull/73#discussion_r1212854340_

**Comment by JuliaSprenger** [comment]
I think this issue is of rather high priority as the running pytest is currently spamming our server with test experiments and templates. @killianrochet Are you interested in taking this one over or should I do it and you review?

**Comment by killianrochet** [comment]
I can do it, yes, but don't we have to merge the #84 first?
