### ISSUE TITLE
Use better return values for elab server functions

### ISSUE THREAD

**Issue by JuliaSprenger** [INT-NIT/DigLabTools#77]
I don't think you need to return the status code explicitly here. In case of an error in the download I would rather raise a IOError in our function here.

_Originally posted by @JuliaSprenger in https://github.com/INT-NIT/DigLabTools/pull/73#discussion_r1212816417_

**Comment by killianrochet** [comment]
I can do it, yes, but don't we have to merge the GH-84 first?
